CREATE TABLE PERSON (
   PERSONID    INT NOT NULL,
   NAME  VARCHAR(20) ,
   SURNAME   VARCHAR(20) ,
   MOBILENUMBER VARCHAR(20) ,
   CITYNAME  VARCHAR (20)  ,
   DISTRICTNAME  VARCHAR (20),
   PERSONFILE BLOB,
   PRIMARY KEY (PERSONID)
)