CREATE TABLE person (
   PERSONID INT  NOT NULL,
   NAME VARCHAR (20),
   SURNAME VARCHAR (20)
   MOBİLENUMBER VARCHAR (14),
   CITYID INT  NOT NULL,
   DISTRICTID INT  NOT NULL,
   PRIMARY KEY (PERSONID)
);